name: Build and Publish Docker Image

on:
  push:
    branches:
      - GITHUB_CI 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/azure-web-search:latest .

    # Push
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/azure-web-search:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/azure-web-search:${{ github.run_number }}
